spring:
#####################################################################################################
# rabbitMQ 属性配置
  rabbitmq:
    host: 192.168.0.200
#####################################################################################################


