server:
  port: 8888

spring:
  application:
    name: sevenfunny-config

  cloud:
    config:
      server:
        git:
         uri: https://github.com/SevenRyuu/SevenFunny/
         searchPaths: service-config
         username:
         password:
      label: master

