server:
  port: 8888

spring:
  application:
    name: sevenfunny-config

  cloud:
    config:
      server:
        git:
         uri: https://github.com/SevenRyuu/SevenFunny/
         searchPaths: service-config
         username:
         password:
      label: master

  rabbitmq:
    host: 192.168.0.200
management: #暴露触发消息总线的地址 endpoints:
  web:
    exposure:
      include: bus-refresh

