server:
  port: 8766

spring:
  application:
    name: sevenfunny-roast
#####################################################################################################
# mongodb 属性配置
  data:
    mongodb:
      host: 192.168.0.200
      database: sevenfunny-roast
#####################################################################################################

