server:
  port: 8764

spring:
  application:
    name: sevenfunny-rabbitmq
#####################################################################################################
# rabbitMQ 属性配置
  rabbitmq:
    host: 192.168.0.200
#####################################################################################################


