server:
  port: 8768

spring:
  application:
    name: sevenfunny-web

  
  rabbitmq:
   host: 192.168.0.200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    sevenfunny-user:
      path: /uat/**
      serviceId: sevenfunny-user
  sensitive-headers:

jwt:
  config:
    key: test
    #ttl: 360000
    header: Authorization
    tokenHead: "Bearer "

