server:
  port: 8765

spring:
  application:
    name: sevenfunny-search
#####################################################################################################
# elasticsearch 属性配置
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.200:9300
      cluster-name: docker-cluster
#####################################################################################################

